/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pa.logo;

public class App {
    public String getGreeting() {
        return "There is no console app";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
